USE_CAMERA_STUB := true
LOCAL_PATH := device/Xiaomi/HM2014813

# inherit from the proprietary version
-include vendor/Xiaomi/HM2014813/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8916
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := generic
TARGET_HARDWARE := qcom
ARCH_ARM_HAVE_TLS_REGISTER := true


TARGET_BOOTLOADER_BOARD_NAME := msm8916	

BOARD_KERNEL_CMDLINE := ramoops_memreserve=2M androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 androidboot.bootdevice=7824900.sdhci
BOARD_KERNEL_BASE := 0x80000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100 --dt device/Xiaomi/HM2014813/dt.img

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072

#kernel
TARGET_PREBUILT_KERNEL := device/Xiaomi/HM2014813/kernel
TARGET_CUSTOM_KERNEL_HEADERS := device/Xiaomi/HM2014813/include


# init
TARGET_PLATFORM_DEVICE_BASE := /devices/soc.0/


# Recovery
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_NO_SELECT_BUTTON := true
#twrp
#TW_CUSTOM_THEME := device/Xiaomi/HM2014813/twres
TW_CUSTOM_THEME := device/Xiaomi/HM2014813/recovery/twres
DEVICE_RESOLUTION := 720×1280
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_USB_STORAGE := true
TW_DEFAULT_EXTERNAL_STORAGE := true
#TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
TW_INCLUDE_CRYPTO := true
TW_TARGET_USES_QCOM_BSP := true
#TARGET_RECOVERY_QCOM_RTC_FIX := true
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 160
TARGET_CPU_SMP := true
#TW_NEW_ION_HEAP := true
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCARD
RECOVERY_GRAPHICS_USE_LINELENGTH := true

# Vold
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/devices/platform/msm_hsusb/gadget/lun0/file
